---
abstract: "Selectively run only a subset of Test::Class tests\nthe inclusde/exclude the specified tags."
author:
  - 'Mark Morgan <makk384@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Class-Filter-Tags
provides:
  Test::Class::Filter::Tags:
    file: lib/Test/Class/Filter/Tags.pm
    version: 0.10
requires:
  Attribute::Method::Tags: 0.1
  Test::Class: 0.35
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
